version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
  redis:
    image: "redis:alpine"
    restart: always
  node:
    image: node:16.4.0-alpine
    restart: always
    volumes:
      - ./code:/usr/src/app/
    ports:
      - 8080:${NODE_PORT}
    working_dir: /usr/src/app/
    command: ["npm", "start"]
    depends_on:
      - mongo
      - redis